// The createSlice function generates a set of actions based on the reducers
// defined in the slice. These actions are automatically generated and
// exported as uiActions constant in this case. The actions can be
// dispatched to modify the state of the slice.


// Import necessary libraries and components
import { createSlice } from '@reduxjs/toolkit';

// Define a new Redux slice for managing UI state
const uiSlice = createSlice({
    // Set the name of the slice (this will be used in the Redux store)
    name: 'ui',
    // Set the initial state of the slice (this will be merged with the overall Redux store)
    initialState: { cartIsVisible: false },
    // Define the reducers for the slice
    reducers: {
        // Define a single reducer called `toggle` that toggles the `cartIsVisible` property in the slice's state
        toggle(state) {
            state.cartIsVisible = !state.cartIsVisible;
        }
    }
});

// Export the actions generated by the `createSlice` function
export const uiActions = uiSlice.actions;

// Export the slice itself for use in creating the Redux store
export default uiSlice;